### ISSUE TITLE
E117: Unknown function: literatevim#load()

### ISSUE THREAD

**Issue by NoahTheDuke** [thcipriani/literate-vimrc#1]
Platform: Windows 10
Vim: 8.0.586

In attempting to set this up, I changed my vimrc from the commented line to the uncommented line, also changing the .vimrc filename to .vimrc.md:

```
" source ~/dotfiles/.vimrc
execute literatevim#load('~/dotfiles/.vimrc.md')
```

When run, Vim generates the following error:

```
Error detected while processing C:\Users\nbogart\_vimrc:
line    2:
E117: Unknown function: literatevim#load
```

**Comment by NoahTheDuke** [comment]
I changed the name of the autoload file to literatevim.vim, and no longer generate the above error. I'll close the issue, but know that others might encounter the same error, so it might be best to change the name of the file.

**Comment by thcipriani** [comment]
Hi @NoahTheDuke !

Thank you for opening this detailed issue -- I really appreciate it! I've updated the plugin to settle on the consistent naming "literatevimrc" (see e76b529).

Leaving this issue closed as it is now, I believe, resolved.

Thanks again!

**Comment by NoahTheDuke** [comment]
Because I have your ear, instead of clogging up the issue tracker, is there a reason for the two different install/set-up methods in the README? `runtime! plugin/literatevimrc.vim` versus `execute literatevimrc#load("~/.vimrc.md")`

Or are they somehow equivalent? (I don't know much about vimscript, sadly.)

**Comment by thcipriani** [comment]
Damnit! Another good catch! :smiley: 

`runtime` takes a file path and executes it as ex commands, `execute` takes a string (or list).

In this instance, the `runtime` instruction was an artifact from when I was writing/debugging the plugin initially.

I removed the `runtime` instruction from the README and it should now be consistent. Thanks for all your help!
